### ISSUE TITLE
Space handling

### ISSUE THREAD

**Issue by madHEYsiaOYO** [WICG/WebOTP#15]
Team, while reading sms, can we handle text message with/ without space after 'For:' ?

'For: https://.....'  => Promise rejects/ resolve
'For:https://.....' => Promise in pending state (no timeout)

Sometime it gets tough for developer to figure out this missing space. 
@samuelgoto

**Comment by sso-google** [comment]
Latest proposal has revised this formatting, but duly noted that we should probably ignore whitespace for the purpose of matching. @samuelgoto

**Comment by hober** [comment]
The SMS format has been split off into [its own repository](https://github.com/wicg/sms-one-time-codes) where you can find an updated [explainer](https://github.com/wicg/sms-one-time-codes) and [spec](https://wicg.github.io/sms-one-time-codes/).

The details of how whitespace is handled can be found in [§ 3.2. Parsing](https://wicg.github.io/sms-one-time-codes/#parsing).

If after reviewing that explainer and spec you still have concerns on this topic, please [file an issue](https://github.com/wicg/sms-one-time-codes/issues/new) in the spec's dedicated repo.
