### ISSUE TITLE
JavaScript API can't be used for polyfilling autocomplete=one-time-code in practice

### ISSUE THREAD

**Issue by hober** [WICG/WebOTP#18]
Hi,

@dbaron, @hadleybeeman, and I took a look at w3ctag/design-reviews#391 today in our Wellington F2F. We have a variety of feedback, of which this issue is one.

It looks like one of the main purposes of the JavaScript API is so it can be used to polyfill `autocomplete=one-time-code`. It seems unlikely to us that a browser will ship with the JavaScript API but without `autocomplete=one-time-code`, so it seems to us that the API can't realistically be used to polyfill the autofill feature in the wild since browsers which lack the autofill feature also lack this JavaScript API.

Do you anticipate that there will be browsers with the JavaScript API but without `autocomplete=one-time-code`?

**Comment by pwnall** [comment]
Chrome is strongly consider shipping the JavaScript API and not `autocomplete=one-time-code`. We currently think that the JS API results in better user experiences than the autocomplete model.

**Comment by samuelgoto** [comment]
> Do you anticipate that there will be browsers with the JavaScript API but without autocomplete=one-time-code?

To answer this question, yes, chrome isn't planning to implement the declarative API at the moment. Not opposing to it, just hasn't gotten up enough in the prioritization to get to it.

I prototyped myself earlier last year and found it to be non trivial to support, hence the preference for the JS API.

https://chromium-review.googlesource.com/c/chromium/src/+/1828057
