### ISSUE TITLE
Requirements for OTPCredentialRequestOptions.transport are incompatible with WebIDL

### ISSUE THREAD

**Issue by mkruisselbrink** [WICG/WebOTP#37]
In https://wicg.github.io/WebOTP/#OTPCredentialRequestOptions is written "This OPTIONAL member contains a hint as to how the server might receive the OTP. The values SHOULD be members of OTPCredentialTransportType but client platforms MUST ignore unknown values.".

However WebIDL requires that converting a string to an enum throws a `TypeError` (https://heycam.github.io/webidl/#es-enumeration) if the string is not a valid enum member. If you do want the behavior you're describing, you should probably define transport as a `sequence<DOMString>` instead?

**Comment by rmondello** [comment]
Issue seems very similar to #31.

**Comment by mkruisselbrink** [comment]
Ah, yes. Definitely a duplicate of that.
