### ISSUE TITLE
SMS without hashes

### ISSUE THREAD

**Issue by flaksp** [WICG/WebOTP#5]
I'm not Android developer and don't know any technical details, but in my company Android devs use native Android API that does not require permissions and special message formatting for handling messages that contain code.

![Screenshot_20190921-112509](https://user-images.githubusercontent.com/12474739/65370568-e184e700-dc62-11e9-9f42-36a8adf2a52d.png)

Maybe we should look in this direction? 

* It does not make your SMS message look ugly. Format it as you like.
* It's still native API for retrieving codes.
* No cons for iOS users. They will receive clean SMSs and their keyboard suggestions will work as always.

**Comment by hober** [comment]
The SMS format has been split off into [its own repository](https://github.com/wicg/sms-one-time-codes) where you can find an updated [explainer](https://github.com/wicg/sms-one-time-codes) and [spec](https://wicg.github.io/sms-one-time-codes/).

If after reviewing that explainer and spec you still have concerns on this topic, please [file an issue](https://github.com/wicg/sms-one-time-codes/issues/new) in the spec's dedicated repo.
