### ISSUE TITLE
Is it possible to let the copy action copy just the OTP code?

### ISSUE THREAD

**Issue by ooade** [WICG/WebOTP#7]
It currently copies the whole thing. But, it would be a better experience for me if it says "Copy OTP" and does just that. Thanks!

**Comment by sso-google** [comment]
I think you might be referring to a system notification with a copy button? This API in the latest formulation only returns the OTP to the developer via an imperative API. So I don't think this is applicable, so we can close out this issue? But add any clarification if need be
